apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test
  namespace: pd-team
spec:
  version: latest
  timezone: UTC
  enableTLSCluster: false
  pvReclaimPolicy: Delete
  enableAdvertiseAddress: true
  autoFailover: false
  configUpdateStrategy: RollingUpdate
  pd:
    baseImage: hub.pingcap.net/csn/pd
    version: 5.0-hot-4a98c86
    replicas: 1
    service:
      type: NodePort
    storageClassName: shared-nvme-disks
    limits:
      cpu: 6000m
      memory: 8Gi
    requests:
      cpu: 6000m
      memory: 8Gi
      storage: 200Gi
    config:
      log:
        level: "info"
        file:
          filename: /var/log/pdlog/pd.log
      dashboard:
        enable-telemetry: false
        enable-experimental: true
    storageVolumes:
      - name: log
        storageClassName: shared-sas-disks
        storageSize: "20Gi"
        mountPath: "/var/log/pdlog"
  tikv:
    env:
      - name: TEST_TIKV_TAGS
        value: "test_need_restart"
    baseImage: hub.pingcap.net/csn/tikv
    version: 5.0-rc-2-1142bc4
    replicas: 3
    storageClassName: nvme-disks
    maxFailoverCount: 0
    evictLeaderTimeout: 1h
    limits:
      cpu: 8000m
      memory: 20Gi
      storage: 500Gi
    requests:
      cpu: 8000m
      memory: 20Gi
      storage: 500Gi
    storageVolumes:
      - name: log
        storageClassName: shared-sas-disks
        storageSize: "20Gi"
        mountPath: "/var/log/tikvlog"
    config: |
      log-level = "info"
      log-file = "/var/log/tikvlog/tikv.log"
      status-addr = "0.0.0.0:20180"
      [rocksdb]
        max-background-jobs = 6
        max-sub-compactions = 3
      [storage.block-cache]
        capacity = "14GB"
        shared = true
      [raftstore]
        capacity = "500GB"
        leader-transfer-max-log-lag = 256
        raft-max-inflight-msgs = 8912
        perf-level = 5
      [readpool.unified]
        min_thread-count = 1
        max-thread-count = 5
      [gc]
        enable-compaction-filter = true
        compaction-filter-skip-version-check = true

  tidb:
    baseImage: hub.pingcap.net/csn/tidb
    version: 5.0-rc-1a9852f
    replicas: 2
    maxFailoverCount: 0
    enableAdvertiseAddress: true
    service:
      type: ClusterIP
    storageClassName: shared-sas-disks
    limits:
      cpu: 8000m
      memory: 24Gi
    requests:
      cpu: 8000m
      memory: 24Gi
    config:
      token-limit: 1000000
      prepared-plan-cache:
        enabled: true
      experimental:
        allow-auto-random: true
      log:
        level: "info"
        file:
          filename: /var/log/tidblog/tidb.log
    storageVolumes:
      - name: log
        storageClassName: shared-sas-disks
        storageSize: "20Gi"
        mountPath: "/var/log/tidblog"
